import type { NextPage } from 'next'
import Head from 'next/head'
import { useReducer } from 'react'
import { ApiConsumer } from '../components/apiContext'
import { DirektKreditSlider,  DirektKreditTilgungSlider, DirektKreditZinsenSlider } from '../components/direktKredite'
import styles from '../styles/Home.module.css'
import { Footer } from './_footer'
import Graph from './_graph'
import MieteDisplay from './_miete'
import { PieChart } from './_pie'
import TilgungChart from './_tilgung'

const useStateWithMerge = (initialState: any) => useReducer(
    (state: any, update: any) => ({ ...state, ...update }),
    initialState
);

const NetAssetsProjected: NextPage = () => {
    const [ apiOptions, setApiOptions ] = useStateWithMerge({ 
        direktKreditTilgung: 0.5,
        direktKreditZinsen: 0.8,
        direktKredite: 0,
        url: "/api/assets/loan-cost" 
    })
    const urlForOptions = (options: any) => {
        const {url, ...queryOptions} = options;
        return url + "?" + new URLSearchParams(queryOptions)
    }

    return (
        <ApiConsumer value={{ apiOptions, updateApiOptions: setApiOptions }}>
            <div className={styles.container}>
                <Head>
                    <title>TWW Miete und Schulden Simulation</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>
                    Miete und Schulden
                    </h1>

                    <div className={styles.grid}>
                        <MieteDisplay dataSource={urlForOptions(apiOptions)} />
                    </div>

                    <div>
                        <div style={{float:'left', padding: "20px"}}>
                            <h1 style={{width:'100%', textAlign:'center'}}>Annual Costs</h1>
                            <Graph width="700" height="600" dataSource={urlForOptions(apiOptions)} />
                        </div>
                        <div style={{float:'right', padding: "20px"}}>
                            <h1 style={{width:'100%', textAlign:'center'}}>Total Debt</h1>
                            <PieChart width="700" height="600" dataSource={urlForOptions(apiOptions)} />
                        </div>
                    </div>

                    <div>
                        <h2 style={{width:'100%', textAlign:'center'}}>Tilgung</h2>
                        <TilgungChart width="1400" height="100" dataSource={urlForOptions(apiOptions)} />
                    </div>

                    <div>
                        <div style={{float:'left', padding: "20px"}}>
                            <DirektKreditSlider/>
                        </div>
                        <div style={{float:'left', padding: "20px"}}>
                            <DirektKreditZinsenSlider/>
                        </div>
                        <div style={{float:'left', padding: "20px"}}>
                            <DirektKreditTilgungSlider/>
                        </div>
                    </div>

                </main>

                <Footer />
            </div>
        </ApiConsumer>
    )
}
  
export default NetAssetsProjected