import type { NextPage } from 'next'
import Head from 'next/head'
import { useReducer } from 'react'
import { ApiConsumer } from '../components/apiContext'
import { DirektKreditSlider,  DirektKreditTilgungSlider, DirektKreditZinsenSlider } from '../components/direktKredite'
import styles from '../styles/Home.module.css'
import { Footer } from './_footer'
import Graph from './_graph'
import MieteDisplay from './_miete'

const useStateWithMerge = (initialState: any) => useReducer(
    (state: any, update: any) => ({ ...state, ...update }),
    initialState
);

const NetAssetsProjected: NextPage = () => {
    const [ apiOptions, setApiOptions ] = useStateWithMerge({ 
        direktKreditTilgung: 0.5,
        direktKreditZinsen: 0.8,
        direktKredite: 0,
        url: "/api/assets/loan-cost" 
    })
    const urlForOptions = (options: any) => {
        const {url, ...queryOptions} = options;
        return url + "?" + new URLSearchParams(queryOptions)
    }

    return (
        <ApiConsumer value={{ apiOptions, updateApiOptions: setApiOptions }}>
            <div className={styles.container}>
                <Head>
                    <title>TWW Miete und Schulden Simulation</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>
                    Miete und Schulden
                    </h1>

                    <div className={styles.grid}>
                        <MieteDisplay dataSource={urlForOptions(apiOptions)} />
                    </div>

                    <div className={styles.grid}>
                        <Graph width="800" height="600" dataSource={urlForOptions(apiOptions)} />
                    </div>

                    <div>
                        <div>
                            <DirektKreditSlider/>
                        </div>
                        <div>
                            <DirektKreditZinsenSlider/>
                        </div>
                        <div>
                            <DirektKreditTilgungSlider/>
                        </div>
                    </div>

                </main>

                <Footer />
            </div>
        </ApiConsumer>
    )
}
  
export default NetAssetsProjected